name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Run tests
        run: |
            xcodebuild -resolvePackageDependencies \
              -project 'Examples/ComposableNavigation-Examples/ComposableNavigation-Examples.xcodeproj' \
              -scheme 'ComposableNavigation-Examples' \
              -derivedDataPath DerivedData \
              -clonedSourcePackagesDirPath ClonedSourcePackages

            xcodebuild clean test \
              -sdk iphonesimulator \
              -project 'Examples/ComposableNavigation-Examples/ComposableNavigation-Examples.xcodeproj' \
              -scheme 'ComposableNavigation-Examples' \
              -derivedDataPath DerivedData \
              -clonedSourcePackagesDirPath ClonedSourcePackages \
              -enableCodeCoverage YES \
              -destination 'platform=iOS Simulator,name=iPhone 14' \
              | xcpretty --report junit --output test_report.xml
      - name: Extract code coverage
        run: |
            binary=DerivedData/Build/Products/Debug-iphonesimulator/ComposableNavigation.o
            profile=DerivedData/Build/ProfileData/*/Coverage.profdata
            xcrun --run llvm-cov show $binary --instr-profile $profile >> coverage.txt
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4.3.1
        with:
          report_paths: 'test_report.xml'
     
